### PR TITLE
Update count_by_twos.ino

### PR DESCRIPTION
**Pull request by ripred**
add UNUSED(A) macro to remove warnings

### CODE REVIEW

**Comment by ripred** [comment]
Hey!  I found your project and was playin around with it and since I have my preferences set to display all warnings I changed it just a bit to remove the "unused variable" warnings.

**Comment by jkingsman** [comment]
Hey there! Thanks for the contribution.

I'm concerned that folks might find the macro usage a little bit more confusing than just having an unused var warning; I think I'd tend towards not optimizing for `Wall` cases in favor of more readable basic-usage examples.

I'm open to a strong argument that the utility increase exceeds the usability decrease, but otherwise I think this is probably not a change I'd like to make right now.

I do appreciate the care and time, though, and am especially glad to hear someone besides me found some usefulness or at least fiddling/interest in this wrapper 🙂

**Comment by ripred** [comment]
Another thing to consider that is much cleaner would be to wrap the variable names in /\*comments\*/ and just leave the data type of the parameter. That works to remove the warnings as well and is much cleaner since it both removes the warnings and leaves the variable names for context to the reader. I could add a different pull request for that if you'd like.

Cheers

p.s. The reason I found your repo was that I'm a moderator over in https://reddit.com/r/arduino and we were discussing 6502 emulation and I found your library via https://www.arduinolibraries.info/ while thinking about enhancements to a project 😄

**Comment by ripred** [comment]
And yeah I love this. Z-80 was my first back in the late 70's

**Comment by jkingsman** [comment]
Hm, so am I understanding you correctly that you're saying to override the prototype in the Z80.h file with anonymous-variable prototype in the example? Is it possible to un-name params in an implementation that are named in the prototype? I'm not super up to speed on my C, to be honest (I spend most of my time in python and terraform nowadays 🤣), so I may be missing something.

Generally, I'm sort of inclined to leave this as functional of a skeleton as possible (i.e., as-is). If someone wants to use IO, for example, that a bare-bones implementation is included in the example and they need only go implement the body. Frankly, I don't know how realistic it is for Arduino hobbyists to go looking at header files haha (nor for them to be put off by unused var warnings, which are pretty harmless as far as warnings go until you start enforcing linter rules imo). 

Please let me know if I'm misunderstanding! 🙂

**Comment by ripred** [comment]
Hi Jack,

Thanks for replying.  Yes if you have a prototype for a function or method that includes any variable name(s) as examples that is fine. And then in the actual definition of the function or method you can use this technique:

void foo(int /* value */, int /* value2 */ ) {
    // you can compile this now and there will be no warnings for unused variables
    // since no symbols were created to refer to them. If the function or method has
    // a prototype in a header file that is fine (even with an example variable name)
    // as long as the data type(s) and order match the existing prototype.
}

So you could do that and it would sort of be the best of both worlds since the names are still there for context and th warnings are removed.

No worries if you would rather not change anything I just keep my warnings level high to catch things I might have missed and when I saw those and changed them in my local copy I figured I pass the changes on.  No big deal.

All the Best,

Trent

**Comment by jkingsman** [comment]
Ah interesting, I see. Yeah I'd probably just rather keep the example easily extended than having someone possibly not notice or not be sure what to do with the commented params -- since it's an example file I'm not too worried about the warnings. But thank you again for the time!

**Pull request closed without merging**
